language: ruby
cache: bundler
script: "bundle exec rake spec cucumber"
install: "travis_retry bundle install"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-19mode
  - jruby-19mode
gemfiles:
  - gemfiles/4.0.0.gemfile
  - gemfiles/4.0.1.gemfile
  - gemfiles/4.1.gemfile
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
